openapi: 3.1.0
info:
  title: Context Management API
  description: API for managing chat context windows, token counting, and compaction
  version: 1.0.0
  contact:
    name: Empire Development

servers:
  - url: /api/v1
    description: Empire API v1

tags:
  - name: Context
    description: Context window management operations
  - name: Compaction
    description: Context compaction operations

paths:
  /context/{conversation_id}:
    get:
      tags:
        - Context
      summary: Get context window status
      description: Returns current token usage and status for a conversation
      operationId: getContextStatus
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Context status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContextWindowStatus'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /context/{conversation_id}/messages:
    post:
      tags:
        - Context
      summary: Add message to context
      description: Adds a new message and returns updated token count
      operationId: addMessage
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMessageRequest'
      responses:
        '201':
          description: Message added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddMessageResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /context/{conversation_id}/messages/{message_id}/protect:
    patch:
      tags:
        - Context
      summary: Toggle message protection
      description: Marks or unmarks a message as protected from compaction
      operationId: toggleMessageProtection
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: message_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_protected:
                  type: boolean
              required:
                - is_protected
      responses:
        '200':
          description: Protection status updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message_id:
                    type: string
                    format: uuid
                  is_protected:
                    type: boolean
        '404':
          description: Message not found

  /context/{conversation_id}/compact:
    post:
      tags:
        - Compaction
      summary: Trigger context compaction
      description: Initiates background compaction with optional flags
      operationId: triggerCompaction
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompactionRequest'
      responses:
        '202':
          description: Compaction started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompactionStartResponse'
        '409':
          description: Compaction already in progress
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded (cooldown period)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /context/{conversation_id}/compact/status:
    get:
      tags:
        - Compaction
      summary: Get compaction status
      description: Returns current compaction progress or last result
      operationId: getCompactionStatus
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Compaction status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompactionStatus'

  /context/{conversation_id}/compact/history:
    get:
      tags:
        - Compaction
      summary: Get compaction history
      description: Returns list of past compaction events
      operationId: getCompactionHistory
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
            maximum: 50
      responses:
        '200':
          description: Compaction history retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  history:
                    type: array
                    items:
                      $ref: '#/components/schemas/CompactionResult'

components:
  schemas:
    ContextWindowStatus:
      type: object
      properties:
        conversation_id:
          type: string
          format: uuid
        total_tokens:
          type: integer
          description: Current token count
          example: 45230
        max_tokens:
          type: integer
          description: Maximum context window size
          example: 200000
        used_percent:
          type: number
          format: float
          description: Percentage of context used
          example: 22.6
        reserved_for_response:
          type: integer
          description: Tokens reserved for model response
          example: 4096
        available_tokens:
          type: integer
          description: Tokens available for new messages
          example: 150674
        status:
          type: string
          enum: [normal, warning, critical]
          description: >
            normal: <70%, warning: 70-85%, critical: >85%
        threshold_percent:
          type: integer
          description: Compaction trigger threshold
          example: 80
        compaction_available:
          type: boolean
          description: Whether compaction can be triggered
        last_compaction_at:
          type: string
          format: date-time
          nullable: true
      required:
        - conversation_id
        - total_tokens
        - max_tokens
        - used_percent
        - status

    AddMessageRequest:
      type: object
      properties:
        role:
          type: string
          enum: [user, assistant, system]
        content:
          type: string
        is_protected:
          type: boolean
          default: false
      required:
        - role
        - content

    AddMessageResponse:
      type: object
      properties:
        message_id:
          type: string
          format: uuid
        token_count:
          type: integer
          description: Tokens in this message
        context_status:
          $ref: '#/components/schemas/ContextWindowStatus'
        compaction_triggered:
          type: boolean
          description: Whether auto-compaction was triggered

    CompactionRequest:
      type: object
      properties:
        force:
          type: boolean
          default: false
          description: Compact even if below threshold
        fast:
          type: boolean
          default: false
          description: Use Haiku model for faster compaction

    CompactionStartResponse:
      type: object
      properties:
        task_id:
          type: string
          description: Celery task ID for tracking
        estimated_duration_seconds:
          type: integer
          description: Estimated time to complete
          example: 25
        model:
          type: string
          enum: [claude-sonnet-4, claude-3-5-haiku]

    CompactionStatus:
      type: object
      properties:
        status:
          type: string
          enum: [idle, in_progress, completed, failed]
        task_id:
          type: string
          nullable: true
        progress:
          type: integer
          minimum: 0
          maximum: 100
          nullable: true
        stage:
          type: string
          enum: [preparing, summarizing, processing, finalizing]
          nullable: true
        started_at:
          type: string
          format: date-time
          nullable: true
        completed_at:
          type: string
          format: date-time
          nullable: true
        result:
          $ref: '#/components/schemas/CompactionResult'
          nullable: true

    CompactionResult:
      type: object
      properties:
        id:
          type: string
          format: uuid
        pre_tokens:
          type: integer
          example: 145230
        post_tokens:
          type: integer
          example: 58450
        reduction_percent:
          type: number
          format: float
          example: 59.7
        messages_condensed:
          type: integer
          example: 42
        summary_preview:
          type: string
          description: First 500 characters of summary
        model_used:
          type: string
        duration_ms:
          type: integer
          example: 23450
        triggered_by:
          type: string
          enum: [auto, manual, force]
        created_at:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: object
              additionalProperties: true
