openapi: 3.1.0
info:
  title: Session Resume API
  description: API for session management, resume functionality, and session picker
  version: 1.0.0
  contact:
    name: Empire Development

servers:
  - url: /api/v1
    description: Empire API v1

tags:
  - name: Sessions
    description: Session listing and management
  - name: Resume
    description: Session resume operations
  - name: Memories
    description: Session memory operations

paths:
  /sessions:
    get:
      tags:
        - Sessions
      summary: List recent sessions
      description: Returns user's recent chat sessions for the session picker
      operationId: listSessions
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 50
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
        - name: project_id
          in: query
          schema:
            type: string
            format: uuid
          description: Filter by project (optional)
        - name: include_archived
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Sessions retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionListResponse'

  /sessions/{session_id}:
    get:
      tags:
        - Sessions
      summary: Get session details
      description: Returns detailed information about a specific session
      operationId: getSession
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Session retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionDetailResponse'
        '404':
          description: Session not found

    delete:
      tags:
        - Sessions
      summary: Delete session
      description: Permanently deletes a session and all associated data
      operationId: deleteSession
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Session deleted successfully
        '404':
          description: Session not found

  /sessions/{session_id}/resume:
    post:
      tags:
        - Resume
      summary: Resume session
      description: Resumes a session from its most recent state or specified checkpoint
      operationId: resumeSession
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResumeRequest'
      responses:
        '200':
          description: Session resumed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResumeResponse'
        '404':
          description: Session or checkpoint not found
        '409':
          description: Session conflict (updated elsewhere)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictResponse'

  /sessions/{session_id}/refresh:
    post:
      tags:
        - Resume
      summary: Refresh session
      description: Syncs local state with server after conflict notification
      operationId: refreshSession
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Session refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResumeResponse'

  /sessions/{session_id}/memory:
    get:
      tags:
        - Memories
      summary: Get session memory
      description: Returns the persistent memory/summary for a session
      operationId: getSessionMemory
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Session memory retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionMemoryResponse'
        '404':
          description: Session or memory not found

    put:
      tags:
        - Memories
      summary: Update session memory
      description: Updates the persistent memory/summary for a session
      operationId: updateSessionMemory
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMemoryRequest'
      responses:
        '200':
          description: Session memory updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionMemoryResponse'

  /sessions/picker:
    get:
      tags:
        - Sessions
      summary: Get session picker data
      description: Returns optimized data for the session picker UI on app launch
      operationId: getSessionPickerData
      parameters:
        - name: include_recovery
          in: query
          schema:
            type: boolean
            default: true
          description: Include crash recovery sessions
      responses:
        '200':
          description: Session picker data retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionPickerResponse'

  /sessions/{session_id}/checkpoints/timeline:
    get:
      tags:
        - Resume
      summary: Get checkpoint timeline
      description: Returns checkpoints formatted for timeline view
      operationId: getCheckpointTimeline
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Checkpoint timeline retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckpointTimelineResponse'

components:
  schemas:
    SessionListResponse:
      type: object
      properties:
        sessions:
          type: array
          items:
            $ref: '#/components/schemas/SessionSummary'
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer

    SessionSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          description: Auto-generated or user-set title
        last_message_preview:
          type: string
          maxLength: 200
        message_count:
          type: integer
        token_count:
          type: integer
        checkpoint_count:
          type: integer
        project_id:
          type: string
          format: uuid
          nullable: true
        project_name:
          type: string
          nullable: true
        is_cko_session:
          type: boolean
          description: Chief Knowledge Officer session
        retention_type:
          type: string
          enum: [project, cko, indefinite]
        has_recovery:
          type: boolean
          description: Whether session has pending recovery
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    SessionDetailResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        project_id:
          type: string
          format: uuid
          nullable: true
        project_name:
          type: string
          nullable: true
        is_cko_session:
          type: boolean
        retention_type:
          type: string
          enum: [project, cko, indefinite]
        context_status:
          $ref: '#/components/schemas/ContextStatus'
        checkpoint_count:
          type: integer
        has_memory:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ContextStatus:
      type: object
      properties:
        total_tokens:
          type: integer
        max_tokens:
          type: integer
        used_percent:
          type: number
          format: float
        status:
          type: string
          enum: [normal, warning, critical]
        message_count:
          type: integer
        compaction_count:
          type: integer

    ResumeRequest:
      type: object
      properties:
        checkpoint_id:
          type: string
          format: uuid
          nullable: true
          description: Specific checkpoint to resume from (null = latest state)
        force:
          type: boolean
          default: false
          description: Force resume even with potential conflicts

    ResumeResponse:
      type: object
      properties:
        session_id:
          type: string
          format: uuid
        title:
          type: string
        context_status:
          $ref: '#/components/schemas/ContextStatus'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/MessageSummary'
        resumed_from:
          type: string
          enum: [latest, checkpoint]
        checkpoint_id:
          type: string
          format: uuid
          nullable: true
        resumed_at:
          type: string
          format: date-time

    ConflictResponse:
      type: object
      properties:
        error:
          type: string
          example: "session_updated_elsewhere"
        message:
          type: string
          example: "This session was updated from another device"
        local_updated_at:
          type: string
          format: date-time
        server_updated_at:
          type: string
          format: date-time
        resolution_options:
          type: array
          items:
            type: string
            enum: [refresh, force_local, discard_local]

    MessageSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        role:
          type: string
          enum: [user, assistant, system]
        content_preview:
          type: string
          maxLength: 500
        token_count:
          type: integer
        is_protected:
          type: boolean
        is_compacted:
          type: boolean
          description: Whether this is a compaction summary
        created_at:
          type: string
          format: date-time

    SessionMemoryResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        session_id:
          type: string
          format: uuid
        summary:
          type: string
        key_decisions:
          type: array
          items:
            $ref: '#/components/schemas/KeyDecision'
        files_mentioned:
          type: array
          items:
            $ref: '#/components/schemas/FileMention'
        code_preserved:
          type: array
          items:
            $ref: '#/components/schemas/CodeSnippet'
        retention_type:
          type: string
          enum: [project, cko, indefinite]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    KeyDecision:
      type: object
      properties:
        decision:
          type: string
        rationale:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time

    FileMention:
      type: object
      properties:
        path:
          type: string
        action:
          type: string
          enum: [created, modified, deleted, mentioned]
        timestamp:
          type: string
          format: date-time

    CodeSnippet:
      type: object
      properties:
        language:
          type: string
        code:
          type: string
        context:
          type: string
          description: Brief description of what this code does

    UpdateMemoryRequest:
      type: object
      properties:
        summary:
          type: string
        key_decisions:
          type: array
          items:
            $ref: '#/components/schemas/KeyDecision'
        files_mentioned:
          type: array
          items:
            $ref: '#/components/schemas/FileMention'
        code_preserved:
          type: array
          items:
            $ref: '#/components/schemas/CodeSnippet'

    SessionPickerResponse:
      type: object
      properties:
        recent_sessions:
          type: array
          items:
            $ref: '#/components/schemas/SessionSummary'
          maxItems: 10
        recovery_sessions:
          type: array
          items:
            $ref: '#/components/schemas/RecoverySessionSummary'
        project_sessions:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/SessionSummary'
          description: Sessions grouped by project

    RecoverySessionSummary:
      type: object
      properties:
        session_id:
          type: string
          format: uuid
        checkpoint_id:
          type: string
          format: uuid
        title:
          type: string
        last_message_preview:
          type: string
        token_count:
          type: integer
        crashed_at:
          type: string
          format: date-time

    CheckpointTimelineResponse:
      type: object
      properties:
        session_id:
          type: string
          format: uuid
        checkpoints:
          type: array
          items:
            $ref: '#/components/schemas/TimelineCheckpoint'

    TimelineCheckpoint:
      type: object
      properties:
        id:
          type: string
          format: uuid
        label:
          type: string
          nullable: true
        auto_tag:
          type: string
          nullable: true
        token_count:
          type: integer
        message_count:
          type: integer
        is_abnormal_close:
          type: boolean
        preview:
          type: string
          maxLength: 200
        created_at:
          type: string
          format: date-time
        expires_at:
          type: string
          format: date-time
        is_current:
          type: boolean
          description: Whether this is the current state
