"""
CrewAI Asset Storage Service for Task 36.3
Handles storage of generated assets (skills, commands, agents, prompts, workflows, summaries) to B2
"""

import os
import io
from typing import Dict, Any, Optional, Union
from datetime import datetime
from pathlib import Path
import structlog

from app.services.b2_storage import B2StorageService

logger = structlog.get_logger(__name__)


class AssetType:
    """Asset types generated by CrewAI agents"""
    SKILL = "skill"
    COMMAND = "command"
    AGENT = "agent"
    PROMPT = "prompt"
    WORKFLOW = "workflow"
    SUMMARY = "summary"


class CrewAIAssetStorage:
    """
    Service for storing CrewAI-generated assets to B2

    Folder Structure in B2:
    - processed/crewai-summaries/{department}/{department}_summary_{timestamp}.pdf
    - processed/crewai-skills/{department}/{department}_skill-name.yaml
    - processed/crewai-commands/{department}/{department}_command-name.md
    - processed/crewai-agents/{department}/{department}_agent-name.yaml
    - processed/crewai-prompts/{department}/{department}_prompt-name.md
    - processed/crewai-workflows/{department}/{department}_workflow-name.json
    """

    def __init__(self, b2_service: Optional[B2StorageService] = None):
        """Initialize with B2 storage service"""
        self.b2_service = b2_service or B2StorageService()

        # 10-department taxonomy from PRD
        self.departments = [
            "it-engineering",
            "sales-marketing",
            "customer-support",
            "operations-hr-supply",
            "finance-accounting",
            "project-management",
            "real-estate",
            "private-equity-ma",
            "consulting",
            "personal-continuing-ed"
        ]

    def get_asset_folder(self, asset_type: str, department: str) -> str:
        """Get B2 folder path for asset type and department"""
        asset_folder_map = {
            AssetType.SUMMARY: f"processed/crewai-summaries/{department}",
            AssetType.SKILL: f"processed/crewai-skills/{department}",
            AssetType.COMMAND: f"processed/crewai-commands/{department}",
            AssetType.AGENT: f"processed/crewai-agents/{department}",
            AssetType.PROMPT: f"processed/crewai-prompts/{department}",
            AssetType.WORKFLOW: f"processed/crewai-workflows/{department}"
        }

        return asset_folder_map.get(asset_type, f"processed/crewai-unknown/{department}")

    def get_filename(
        self,
        asset_type: str,
        department: str,
        asset_name: str,
        extension: Optional[str] = None
    ) -> str:
        """
        Generate filename following PRD patterns

        Patterns:
        - Summary: {department}_summary_{timestamp}.pdf
        - Skill: {department}_skill-name.yaml
        - Command: {department}_command-name.md
        - Agent: {department}_agent-name.yaml
        - Prompt: {department}_prompt-name.md
        - Workflow: {department}_workflow-name.json
        """
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")

        if asset_type == AssetType.SUMMARY:
            return f"{department}_summary_{timestamp}.pdf"
        elif asset_type == AssetType.SKILL:
            return f"{department}_{asset_name}.yaml"
        elif asset_type == AssetType.COMMAND:
            return f"{department}_{asset_name}.md"
        elif asset_type == AssetType.AGENT:
            return f"{department}_{asset_name}.yaml"
        elif asset_type == AssetType.PROMPT:
            return f"{department}_{asset_name}.md"
        elif asset_type == AssetType.WORKFLOW:
            return f"{department}_{asset_name}.json"
        else:
            ext = extension or "txt"
            return f"{department}_{asset_name}_{timestamp}.{ext}"

    async def store_asset(
        self,
        asset_type: str,
        department: str,
        asset_name: str,
        content: Union[str, bytes],
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Store a generated asset to B2

        Args:
            asset_type: Type of asset (skill, command, agent, prompt, workflow, summary)
            department: Department classification
            asset_name: Name/identifier for the asset
            content: Asset content (string or bytes)
            metadata: Additional metadata to store with file

        Returns:
            Dict with file_id, file_name, folder, url
        """
        try:
            # Validate department
            if department not in self.departments:
                logger.warning("Unknown department", department=department)

            # Get folder and filename
            folder = self.get_asset_folder(asset_type, department)
            filename = self.get_filename(asset_type, department, asset_name)

            # Convert content to bytes if string
            if isinstance(content, str):
                content_bytes = content.encode('utf-8')
            else:
                content_bytes = content

            # Create file object
            file_obj = io.BytesIO(content_bytes)

            # Prepare metadata
            file_metadata = {
                "asset_type": asset_type,
                "department": department,
                "asset_name": asset_name,
                "generated_at": datetime.utcnow().isoformat(),
                **(metadata or {})
            }

            # Upload to B2
            result = await self.b2_service.upload_file(
                file_obj=file_obj,
                file_name=filename,
                folder=folder,
                content_type=self._get_content_type(asset_type),
                file_info=file_metadata
            )

            logger.info(
                "Asset stored to B2",
                asset_type=asset_type,
                department=department,
                filename=filename,
                folder=folder
            )

            return {
                "file_id": result.get("fileId"),
                "file_name": filename,
                "folder": folder,
                "url": result.get("url"),
                "size": len(content_bytes),
                "metadata": file_metadata
            }

        except Exception as e:
            logger.error(
                "Failed to store asset",
                asset_type=asset_type,
                department=department,
                error=str(e)
            )
            raise

    def _get_content_type(self, asset_type: str) -> str:
        """Get content type for asset type"""
        content_types = {
            AssetType.SUMMARY: "application/pdf",
            AssetType.SKILL: "application/x-yaml",
            AssetType.COMMAND: "text/markdown",
            AssetType.AGENT: "application/x-yaml",
            AssetType.PROMPT: "text/markdown",
            AssetType.WORKFLOW: "application/json"
        }
        return content_types.get(asset_type, "text/plain")

    async def store_summary(
        self,
        department: str,
        content: bytes,
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Store a PDF summary"""
        return await self.store_asset(
            asset_type=AssetType.SUMMARY,
            department=department,
            asset_name="summary",
            content=content,
            metadata=metadata
        )

    async def store_skill(
        self,
        department: str,
        skill_name: str,
        yaml_content: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Store a YAML skill definition"""
        return await self.store_asset(
            asset_type=AssetType.SKILL,
            department=department,
            asset_name=skill_name,
            content=yaml_content,
            metadata=metadata
        )

    async def store_command(
        self,
        department: str,
        command_name: str,
        markdown_content: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Store a Markdown slash command"""
        return await self.store_asset(
            asset_type=AssetType.COMMAND,
            department=department,
            asset_name=command_name,
            content=markdown_content,
            metadata=metadata
        )

    async def store_agent_config(
        self,
        department: str,
        agent_name: str,
        yaml_content: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Store a CrewAI agent YAML configuration"""
        return await self.store_asset(
            asset_type=AssetType.AGENT,
            department=department,
            asset_name=agent_name,
            content=yaml_content,
            metadata=metadata
        )

    async def store_prompt(
        self,
        department: str,
        prompt_name: str,
        markdown_content: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Store an AI prompt template"""
        return await self.store_asset(
            asset_type=AssetType.PROMPT,
            department=department,
            asset_name=prompt_name,
            content=markdown_content,
            metadata=metadata
        )

    async def store_workflow(
        self,
        department: str,
        workflow_name: str,
        json_content: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Store an n8n workflow JSON"""
        return await self.store_asset(
            asset_type=AssetType.WORKFLOW,
            department=department,
            asset_name=workflow_name,
            content=json_content,
            metadata=metadata
        )


def get_crewai_asset_storage() -> CrewAIAssetStorage:
    """Dependency injection for CrewAI asset storage"""
    return CrewAIAssetStorage()
