-- Migration: Create Research Jobs Table
-- Feature: Research Projects (Agent Harness)
-- Date: 2025-01-10

-- Drop existing table if exists (for development only)
-- DROP TABLE IF EXISTS public.research_jobs CASCADE;

CREATE TABLE IF NOT EXISTS public.research_jobs (
    -- Primary Key
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Ownership
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    customer_id TEXT NOT NULL,

    -- Research Request
    query TEXT NOT NULL,
    context TEXT,
    research_type TEXT DEFAULT 'general',

    -- Status Management
    status TEXT NOT NULL DEFAULT 'initializing',
    locked_at TIMESTAMPTZ,
    locked_by TEXT,

    -- Progress Tracking
    total_tasks INTEGER DEFAULT 0,
    completed_tasks INTEGER DEFAULT 0,
    current_task_key TEXT,
    progress_percentage DECIMAL(5,2) DEFAULT 0.00,

    -- Results
    report_content TEXT,
    report_url TEXT,
    summary TEXT,
    key_findings JSONB,

    -- Notifications
    notify_email TEXT NOT NULL,
    notification_sent_at TIMESTAMPTZ,

    -- Execution Metadata
    execution_id TEXT,
    retries SMALLINT DEFAULT 0,
    max_retries SMALLINT DEFAULT 3,
    error_message TEXT,
    error_details JSONB,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,

    -- Constraints
    CONSTRAINT valid_status CHECK (status IN (
        'initializing', 'planning', 'planned', 'executing',
        'synthesizing', 'generating_report', 'complete', 'failed', 'cancelled'
    )),
    CONSTRAINT valid_research_type CHECK (research_type IN (
        'general', 'compliance', 'competitive', 'technical', 'financial'
    ))
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_research_jobs_user_id ON research_jobs(user_id);
CREATE INDEX IF NOT EXISTS idx_research_jobs_status ON research_jobs(status);
CREATE INDEX IF NOT EXISTS idx_research_jobs_created_at ON research_jobs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_research_jobs_user_status ON research_jobs(user_id, status);

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_research_jobs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_research_jobs_updated_at ON research_jobs;
CREATE TRIGGER trigger_research_jobs_updated_at
    BEFORE UPDATE ON research_jobs
    FOR EACH ROW
    EXECUTE FUNCTION update_research_jobs_updated_at();

-- Comments for documentation
COMMENT ON TABLE research_jobs IS 'Stores research project metadata, status, and results for the Agent Harness feature';
COMMENT ON COLUMN research_jobs.status IS 'Project lifecycle: initializing → planning → planned → executing → synthesizing → generating_report → complete/failed/cancelled';
COMMENT ON COLUMN research_jobs.research_type IS 'Type of research: general, compliance, competitive, technical, financial';
COMMENT ON COLUMN research_jobs.progress_percentage IS 'Completion percentage based on completed_tasks / total_tasks';
