-- Migration: Create Plan Tasks Table
-- Feature: Research Projects (Agent Harness)
-- Date: 2025-01-10

-- Drop existing table if exists (for development only)
-- DROP TABLE IF EXISTS public.plan_tasks CASCADE;

CREATE TABLE IF NOT EXISTS public.plan_tasks (
    -- Primary Key
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relationships
    job_id BIGINT NOT NULL REFERENCES research_jobs(id) ON DELETE CASCADE,
    parent_task_id BIGINT REFERENCES plan_tasks(id) ON DELETE SET NULL,

    -- Task Identity
    task_key TEXT NOT NULL,
    sequence_order INTEGER NOT NULL,

    -- Task Definition
    task_type TEXT NOT NULL,
    task_title TEXT,
    task_description TEXT,
    query TEXT,
    config JSONB DEFAULT '{}',

    -- Dependencies (array of task_key values)
    depends_on TEXT[],

    -- Status Management
    status TEXT NOT NULL DEFAULT 'pending',

    -- Results
    result_summary TEXT,
    result_data JSONB,
    artifacts_count INTEGER DEFAULT 0,

    -- Execution Metadata
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    duration_seconds INTEGER,
    retry_count SMALLINT DEFAULT 0,
    error_message TEXT,
    error_details JSONB,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Constraints
    UNIQUE(job_id, task_key),
    CONSTRAINT valid_task_status CHECK (status IN (
        'pending', 'queued', 'running', 'complete', 'failed', 'skipped', 'cancelled'
    )),
    CONSTRAINT valid_task_type CHECK (task_type IN (
        'retrieval_rag', 'retrieval_nlq', 'retrieval_graph', 'retrieval_api',
        'synthesis', 'fact_check', 'write_section', 'write_report', 'review'
    ))
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_plan_tasks_job_id ON plan_tasks(job_id);
CREATE INDEX IF NOT EXISTS idx_plan_tasks_status ON plan_tasks(status);
CREATE INDEX IF NOT EXISTS idx_plan_tasks_sequence ON plan_tasks(job_id, sequence_order);
CREATE INDEX IF NOT EXISTS idx_plan_tasks_type ON plan_tasks(task_type);
CREATE INDEX IF NOT EXISTS idx_plan_tasks_parent ON plan_tasks(parent_task_id) WHERE parent_task_id IS NOT NULL;

-- Comments for documentation
COMMENT ON TABLE plan_tasks IS 'Individual tasks within a research project, created by the Initializer service';
COMMENT ON COLUMN plan_tasks.task_type IS 'Task type determines which executor handles it: retrieval_*, synthesis, fact_check, write_*, review';
COMMENT ON COLUMN plan_tasks.depends_on IS 'Array of task_key values that must complete before this task can run';
COMMENT ON COLUMN plan_tasks.status IS 'Task lifecycle: pending → queued → running → complete/failed/skipped/cancelled';
