-- Migration: Create Research Artifacts Table
-- Feature: Research Projects (Agent Harness)
-- Date: 2025-01-10

-- Drop existing table if exists (for development only)
-- DROP TABLE IF EXISTS public.research_artifacts CASCADE;

CREATE TABLE IF NOT EXISTS public.research_artifacts (
    -- Primary Key
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relationships
    job_id BIGINT NOT NULL REFERENCES research_jobs(id) ON DELETE CASCADE,
    task_id BIGINT REFERENCES plan_tasks(id) ON DELETE SET NULL,

    -- Artifact Identity
    artifact_type TEXT NOT NULL,

    -- Source Information
    source TEXT,
    source_type TEXT,
    source_id TEXT,
    source_url TEXT,

    -- Content
    query_used TEXT,
    raw_response JSONB,
    processed_content TEXT,

    -- Quality Metrics
    relevance_score DECIMAL(5,4),
    confidence_score DECIMAL(5,4),
    citation_info JSONB,

    -- Metadata
    metadata JSONB DEFAULT '{}',

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Constraints
    CONSTRAINT valid_artifact_type CHECK (artifact_type IN (
        'retrieved_chunk', 'query_result', 'graph_path', 'api_response',
        'synthesis_finding', 'fact_check_result', 'report_section', 'final_report'
    )),
    CONSTRAINT valid_source_type CHECK (source_type IS NULL OR source_type IN (
        'document', 'database', 'graph', 'api', 'ai_generated'
    ))
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_research_artifacts_job_id ON research_artifacts(job_id);
CREATE INDEX IF NOT EXISTS idx_research_artifacts_task_id ON research_artifacts(task_id);
CREATE INDEX IF NOT EXISTS idx_research_artifacts_type ON research_artifacts(artifact_type);
CREATE INDEX IF NOT EXISTS idx_research_artifacts_source_type ON research_artifacts(source_type) WHERE source_type IS NOT NULL;

-- Comments for documentation
COMMENT ON TABLE research_artifacts IS 'Stores outputs from task execution: retrieved content, findings, report sections';
COMMENT ON COLUMN research_artifacts.artifact_type IS 'Type of artifact: retrieved_chunk, query_result, graph_path, api_response, synthesis_finding, fact_check_result, report_section, final_report';
COMMENT ON COLUMN research_artifacts.source_type IS 'Origin of the artifact: document, database, graph, api, ai_generated';
COMMENT ON COLUMN research_artifacts.relevance_score IS 'Score from 0-1 indicating relevance to the research query';
COMMENT ON COLUMN research_artifacts.confidence_score IS 'Score from 0-1 indicating confidence in the artifact quality';
