-- Migration: Create Shared Reports Table
-- Feature: Research Projects (Agent Harness) - FR-005, FR-005a
-- Date: 2025-01-10

-- Drop existing table if exists (for development only)
-- DROP TABLE IF EXISTS public.shared_reports CASCADE;

CREATE TABLE IF NOT EXISTS public.shared_reports (
    -- Primary Key
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relationships
    job_id BIGINT NOT NULL REFERENCES research_jobs(id) ON DELETE CASCADE,

    -- Share Token (public URL identifier)
    share_token TEXT NOT NULL UNIQUE,

    -- Access Control
    created_by UUID NOT NULL REFERENCES auth.users(id),
    revoked_at TIMESTAMPTZ,  -- NULL = active, timestamp = revoked
    revoked_by UUID REFERENCES auth.users(id),

    -- Optional expiration (NULL = never expires)
    expires_at TIMESTAMPTZ,

    -- Usage Tracking
    view_count INTEGER DEFAULT 0,
    last_viewed_at TIMESTAMPTZ,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_shared_reports_job_id ON shared_reports(job_id);
CREATE INDEX IF NOT EXISTS idx_shared_reports_token ON shared_reports(share_token);
CREATE INDEX IF NOT EXISTS idx_shared_reports_active ON shared_reports(job_id) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_shared_reports_created_by ON shared_reports(created_by);

-- Function to generate secure share token
CREATE OR REPLACE FUNCTION generate_share_token()
RETURNS TEXT AS $$
BEGIN
    -- Generate a URL-safe random token (32 bytes = 43 base64 characters)
    RETURN encode(gen_random_bytes(32), 'base64');
END;
$$ LANGUAGE plpgsql;

-- Function to increment view count and update last_viewed_at
CREATE OR REPLACE FUNCTION increment_share_view(p_token TEXT)
RETURNS TABLE(
    job_id BIGINT,
    is_valid BOOLEAN,
    report_content TEXT,
    report_url TEXT,
    summary TEXT,
    key_findings JSONB
) AS $$
DECLARE
    v_share_record shared_reports%ROWTYPE;
    v_job_record research_jobs%ROWTYPE;
BEGIN
    -- Get the share record
    SELECT * INTO v_share_record
    FROM shared_reports sr
    WHERE sr.share_token = p_token;

    -- Check if token exists
    IF NOT FOUND THEN
        RETURN QUERY SELECT NULL::BIGINT, FALSE, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::JSONB;
        RETURN;
    END IF;

    -- Check if revoked
    IF v_share_record.revoked_at IS NOT NULL THEN
        RETURN QUERY SELECT NULL::BIGINT, FALSE, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::JSONB;
        RETURN;
    END IF;

    -- Check if expired
    IF v_share_record.expires_at IS NOT NULL AND v_share_record.expires_at < NOW() THEN
        RETURN QUERY SELECT NULL::BIGINT, FALSE, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::JSONB;
        RETURN;
    END IF;

    -- Update view count
    UPDATE shared_reports
    SET view_count = view_count + 1,
        last_viewed_at = NOW()
    WHERE id = v_share_record.id;

    -- Get the job record
    SELECT * INTO v_job_record
    FROM research_jobs rj
    WHERE rj.id = v_share_record.job_id;

    -- Return the report data
    RETURN QUERY SELECT
        v_job_record.id,
        TRUE,
        v_job_record.report_content,
        v_job_record.report_url,
        v_job_record.summary,
        v_job_record.key_findings;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Comments for documentation
COMMENT ON TABLE shared_reports IS 'Manages public shareable links for completed research reports (FR-005, FR-005a)';
COMMENT ON COLUMN shared_reports.share_token IS 'Unique URL-safe token for public access';
COMMENT ON COLUMN shared_reports.revoked_at IS 'NULL = active link, timestamp = revoked (FR-005a)';
COMMENT ON COLUMN shared_reports.expires_at IS 'Optional expiration timestamp, NULL = never expires';
COMMENT ON FUNCTION increment_share_view IS 'Validates share token and returns report data, incrementing view count';
