-- Migration: Create Research Reports Table and Add Report URL Columns
-- Task 181: Research Tasks Report Generation
-- Date: 2025-01-17

-- =============================================================================
-- Part 1: Add report URL columns to research_jobs
-- =============================================================================

-- Add columns for separate markdown and PDF URLs
ALTER TABLE public.research_jobs
ADD COLUMN IF NOT EXISTS report_md_url TEXT,
ADD COLUMN IF NOT EXISTS report_pdf_url TEXT,
ADD COLUMN IF NOT EXISTS celery_task_id TEXT;

-- Index for celery task lookup (Task 187)
CREATE INDEX IF NOT EXISTS idx_research_jobs_celery_task
ON research_jobs(celery_task_id)
WHERE celery_task_id IS NOT NULL;

-- Add comments
COMMENT ON COLUMN research_jobs.report_md_url IS 'B2 URL for markdown report (Task 181)';
COMMENT ON COLUMN research_jobs.report_pdf_url IS 'B2 URL for PDF report (Task 181)';
COMMENT ON COLUMN research_jobs.celery_task_id IS 'Celery task ID for job cancellation (Task 187)';


-- =============================================================================
-- Part 2: Create research_reports table for detailed report metadata
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.research_reports (
    -- Primary Key
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relationship to job
    job_id BIGINT NOT NULL REFERENCES research_jobs(id) ON DELETE CASCADE,

    -- Report Metadata
    title TEXT NOT NULL,
    description TEXT,

    -- B2 Storage Paths
    md_path TEXT,
    md_url TEXT,
    pdf_path TEXT,
    pdf_url TEXT,

    -- Content Statistics
    word_count INTEGER DEFAULT 0,
    artifact_count INTEGER DEFAULT 0,
    task_count INTEGER DEFAULT 0,

    -- Quality Metrics (from ReportExecutor review)
    quality_score DECIMAL(3,2),
    accuracy_score DECIMAL(3,2),
    completeness_score DECIMAL(3,2),
    clarity_score DECIMAL(3,2),

    -- B2 File IDs (for deletion/management)
    md_file_id TEXT,
    pdf_file_id TEXT,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_research_reports_job_id ON research_reports(job_id);
CREATE INDEX IF NOT EXISTS idx_research_reports_created_at ON research_reports(created_at DESC);

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_research_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_research_reports_updated_at ON research_reports;
CREATE TRIGGER trigger_research_reports_updated_at
    BEFORE UPDATE ON research_reports
    FOR EACH ROW
    EXECUTE FUNCTION update_research_reports_updated_at();

-- Comments for documentation
COMMENT ON TABLE research_reports IS 'Stores detailed metadata for generated research reports (Task 181)';
COMMENT ON COLUMN research_reports.md_path IS 'B2 storage path for markdown report';
COMMENT ON COLUMN research_reports.pdf_path IS 'B2 storage path for PDF report';
COMMENT ON COLUMN research_reports.quality_score IS 'Overall quality score from ReportExecutor review (0-1)';


-- =============================================================================
-- Part 3: Row Level Security (RLS) for research_reports
-- =============================================================================

-- Enable RLS
ALTER TABLE public.research_reports ENABLE ROW LEVEL SECURITY;

-- Users can only see reports for their own jobs
CREATE POLICY "Users can view their own reports"
ON public.research_reports
FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM research_jobs rj
        WHERE rj.id = research_reports.job_id
        AND rj.user_id = auth.uid()
    )
);

-- Users can insert reports for their own jobs
CREATE POLICY "Users can insert reports for their own jobs"
ON public.research_reports
FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM research_jobs rj
        WHERE rj.id = research_reports.job_id
        AND rj.user_id = auth.uid()
    )
);

-- Service role bypass
CREATE POLICY "Service role has full access to reports"
ON public.research_reports
FOR ALL
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');
