"""
Pydantic models for CrewAI Generated Assets
"""

from pydantic import BaseModel, Field, field_validator
from typing import Optional, Dict, Any, List, Union
from uuid import UUID
from datetime import datetime
from enum import Enum
import base64


class AssetType(str, Enum):
    """Common asset types generated by CrewAI workflows"""
    SUMMARY = "summary"
    ANALYSIS = "analysis"
    REPORT = "report"
    CHART = "chart"
    PRESENTATION = "presentation"
    CONTRACT_REVIEW = "contract_review"
    ORG_CHART = "org_chart"
    POLICY_BRIEF = "policy_brief"
    CUSTOM = "custom"


class Department(str, Enum):
    """Organization departments"""
    MARKETING = "marketing"
    LEGAL = "legal"
    HR = "hr"
    FINANCE = "finance"
    OPERATIONS = "operations"
    PRODUCT = "product"
    ENGINEERING = "engineering"
    SALES = "sales"
    CUSTOM = "custom"


class ContentFormat(str, Enum):
    """Content format types"""
    TEXT = "text"
    MARKDOWN = "markdown"
    HTML = "html"
    JSON = "json"
    PDF = "pdf"
    DOCX = "docx"
    PNG = "png"
    JPEG = "jpeg"
    SVG = "svg"


class AssetStorageRequest(BaseModel):
    """Request to store a generated asset"""
    execution_id: UUID = Field(..., description="CrewAI execution ID")
    document_id: Optional[str] = Field(None, description="Associated document ID")
    department: Department = Field(..., description="Department that generated the asset")
    asset_type: AssetType = Field(..., description="Type of asset")
    asset_name: str = Field(..., description="Human-readable asset name")
    content: Optional[str] = Field(None, description="Text content (for text-based assets)")
    content_format: ContentFormat = Field(ContentFormat.TEXT, description="Format of the content")
    file_content: Optional[bytes] = Field(None, description="Binary file content (for file-based assets, base64-encoded in JSON)")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    confidence_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Confidence score (0-1)")

    @field_validator('file_content', mode='before')
    @classmethod
    def decode_base64_file_content(cls, v: Optional[Union[str, bytes]]) -> Optional[bytes]:
        """
        Decode base64-encoded file content from JSON.

        When sending binary data via JSON, it must be base64-encoded.
        This validator automatically decodes it back to bytes.
        """
        if v is None:
            return None
        if isinstance(v, bytes):
            return v
        if isinstance(v, str):
            try:
                return base64.b64decode(v)
            except Exception as e:
                raise ValueError(f"Invalid base64-encoded file_content: {e}")
        raise ValueError(f"file_content must be base64 string or bytes, got {type(v)}")

    class Config:
        json_schema_extra = {
            "example": {
                "execution_id": "550e8400-e29b-41d4-a716-446655440000",
                "document_id": "doc-123",
                "department": "marketing",
                "asset_type": "summary",
                "asset_name": "Q4 Campaign Summary",
                "content": "# Q4 Marketing Campaign\n\nKey findings...",
                "content_format": "markdown",
                "metadata": {"campaign": "Q4", "year": 2025},
                "confidence_score": 0.95
            }
        }


class AssetUpdateRequest(BaseModel):
    """Request to update asset metadata or confidence"""
    confidence_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Updated confidence score")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Updated metadata (will be merged)")

    class Config:
        json_schema_extra = {
            "example": {
                "confidence_score": 0.98,
                "metadata": {"reviewed_by": "John Doe", "approved": True}
            }
        }


class AssetResponse(BaseModel):
    """Response with asset details"""
    id: UUID
    execution_id: UUID
    document_id: Optional[str]
    department: Optional[str]
    asset_type: str
    asset_name: str
    content: Optional[str]
    content_format: Optional[str]
    b2_path: Optional[str]
    file_size: Optional[int]
    mime_type: Optional[str]
    metadata: Dict[str, Any]
    confidence_score: Optional[float]
    created_at: datetime

    class Config:
        from_attributes = True
        json_schema_extra = {
            "example": {
                "id": "123e4567-e89b-12d3-a456-426614174000",
                "execution_id": "550e8400-e29b-41d4-a716-446655440000",
                "document_id": "doc-123",
                "department": "marketing",
                "asset_type": "summary",
                "asset_name": "Q4 Campaign Summary",
                "content": "# Q4 Marketing Campaign...",
                "content_format": "markdown",
                "b2_path": None,
                "file_size": None,
                "mime_type": "text/markdown",
                "metadata": {"campaign": "Q4"},
                "confidence_score": 0.95,
                "created_at": "2025-01-13T12:00:00Z"
            }
        }


class AssetListResponse(BaseModel):
    """Response with list of assets"""
    total: int
    assets: List[AssetResponse]
    filters_applied: Dict[str, Any]

    class Config:
        json_schema_extra = {
            "example": {
                "total": 42,
                "assets": [],
                "filters_applied": {
                    "department": "marketing",
                    "asset_type": "summary",
                    "min_confidence": 0.8
                }
            }
        }


class AssetRetrievalFilters(BaseModel):
    """Filters for asset retrieval"""
    execution_id: Optional[UUID] = Field(None, description="Filter by execution ID")
    department: Optional[Department] = Field(None, description="Filter by department")
    asset_type: Optional[AssetType] = Field(None, description="Filter by asset type")
    min_confidence: Optional[float] = Field(None, ge=0.0, le=1.0, description="Minimum confidence score")
    max_confidence: Optional[float] = Field(None, ge=0.0, le=1.0, description="Maximum confidence score")
    limit: int = Field(100, ge=1, le=1000, description="Maximum number of results")
    offset: int = Field(0, ge=0, description="Offset for pagination")

    class Config:
        json_schema_extra = {
            "example": {
                "department": "marketing",
                "asset_type": "summary",
                "min_confidence": 0.8,
                "limit": 50,
                "offset": 0
            }
        }
