"""
Empire v7.3 - Standardized Error Codes
Task 135: Implement Standardized Error Response Model and Handling

Centralized error code constants for consistent error handling across all agents.
"""

# =============================================================================
# COMMON HTTP ERROR CODES
# =============================================================================

# 400 Bad Request
VALIDATION_ERROR = "VALIDATION_ERROR"
INVALID_REQUEST = "INVALID_REQUEST"
MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
INVALID_FORMAT = "INVALID_FORMAT"

# 401 Unauthorized
UNAUTHORIZED = "UNAUTHORIZED"
INVALID_TOKEN = "INVALID_TOKEN"
TOKEN_EXPIRED = "TOKEN_EXPIRED"
MISSING_AUTH_HEADER = "MISSING_AUTH_HEADER"

# 403 Forbidden
FORBIDDEN = "FORBIDDEN"
INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
ACCESS_DENIED = "ACCESS_DENIED"

# 404 Not Found
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
USER_NOT_FOUND = "USER_NOT_FOUND"

# 409 Conflict
CONFLICT = "CONFLICT"
DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"
STATE_CONFLICT = "STATE_CONFLICT"

# 422 Unprocessable Entity
UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"
BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION"

# 429 Too Many Requests
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
QUOTA_EXCEEDED = "QUOTA_EXCEEDED"

# 500 Internal Server Error
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
DATABASE_ERROR = "DATABASE_ERROR"
CONFIGURATION_ERROR = "CONFIGURATION_ERROR"

# 502 Bad Gateway
BAD_GATEWAY = "BAD_GATEWAY"
UPSTREAM_ERROR = "UPSTREAM_ERROR"

# 503 Service Unavailable
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
MAINTENANCE_MODE = "MAINTENANCE_MODE"

# 504 Gateway Timeout
GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"


# =============================================================================
# AGENT-SPECIFIC ERROR CODES
# =============================================================================

# General Agent Errors
AGENT_PROCESSING_ERROR = "AGENT_PROCESSING_ERROR"
AGENT_TIMEOUT = "AGENT_TIMEOUT"
AGENT_UNAVAILABLE = "AGENT_UNAVAILABLE"
AGENT_INITIALIZATION_ERROR = "AGENT_INITIALIZATION_ERROR"
AGENT_CIRCUIT_OPEN = "AGENT_CIRCUIT_OPEN"

# LLM-Related Errors
LLM_ERROR = "LLM_ERROR"
LLM_TIMEOUT = "LLM_TIMEOUT"
LLM_RATE_LIMIT = "LLM_RATE_LIMIT"
LLM_CONTEXT_EXCEEDED = "LLM_CONTEXT_EXCEEDED"
LLM_INVALID_RESPONSE = "LLM_INVALID_RESPONSE"
LLM_API_KEY_INVALID = "LLM_API_KEY_INVALID"

# Content Prep Agent (AGENT-016) Errors
CONTENT_SET_NOT_FOUND = "CONTENT_SET_NOT_FOUND"
CONTENT_SET_INCOMPLETE = "CONTENT_SET_INCOMPLETE"
CONTENT_SET_PROCESSING_ERROR = "CONTENT_SET_PROCESSING_ERROR"
FILE_ORDERING_FAILED = "FILE_ORDERING_FAILED"
FILE_FORMAT_UNSUPPORTED = "FILE_FORMAT_UNSUPPORTED"

# Asset Generator Agent (AGENT-003 to AGENT-007) Errors
ASSET_GENERATION_FAILED = "ASSET_GENERATION_FAILED"
ASSET_TYPE_UNSUPPORTED = "ASSET_TYPE_UNSUPPORTED"
ASSET_SAVE_FAILED = "ASSET_SAVE_FAILED"
TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND"

# Content Summarizer (AGENT-002) Errors
SUMMARIZATION_FAILED = "SUMMARIZATION_FAILED"
CONTENT_TOO_LONG = "CONTENT_TOO_LONG"
CONTENT_TOO_SHORT = "CONTENT_TOO_SHORT"

# Department Classifier (AGENT-008) Errors
CLASSIFICATION_FAILED = "CLASSIFICATION_FAILED"
INVALID_DEPARTMENT = "INVALID_DEPARTMENT"

# Document Analysis Agents (AGENT-009 to AGENT-011) Errors
ANALYSIS_FAILED = "ANALYSIS_FAILED"
RESEARCH_FAILED = "RESEARCH_FAILED"
FACT_CHECK_FAILED = "FACT_CHECK_FAILED"

# Multi-Agent Orchestration (AGENT-012 to AGENT-015) Errors
ORCHESTRATION_FAILED = "ORCHESTRATION_FAILED"
WORKFLOW_TIMEOUT = "WORKFLOW_TIMEOUT"
WORKFLOW_STEP_FAILED = "WORKFLOW_STEP_FAILED"
REVISION_LIMIT_EXCEEDED = "REVISION_LIMIT_EXCEEDED"

# Graph Agent Errors
GRAPH_QUERY_FAILED = "GRAPH_QUERY_FAILED"
GRAPH_CONNECTION_ERROR = "GRAPH_CONNECTION_ERROR"
GRAPH_TRAVERSAL_ERROR = "GRAPH_TRAVERSAL_ERROR"


# =============================================================================
# EXTERNAL SERVICE ERROR CODES
# =============================================================================

# Database Errors
NEO4J_ERROR = "NEO4J_ERROR"
SUPABASE_ERROR = "SUPABASE_ERROR"
REDIS_ERROR = "REDIS_ERROR"

# Storage Errors
B2_STORAGE_ERROR = "B2_STORAGE_ERROR"
FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
FILE_DOWNLOAD_FAILED = "FILE_DOWNLOAD_FAILED"

# External API Errors
EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR"
ANTHROPIC_API_ERROR = "ANTHROPIC_API_ERROR"
LLAMAPARSE_ERROR = "LLAMAPARSE_ERROR"


# =============================================================================
# ERROR CODE METADATA
# =============================================================================

# Mapping of error codes to HTTP status codes
ERROR_CODE_TO_HTTP_STATUS = {
    # 400 Bad Request
    VALIDATION_ERROR: 400,
    INVALID_REQUEST: 400,
    MISSING_REQUIRED_FIELD: 400,
    INVALID_FORMAT: 400,
    # 401 Unauthorized
    UNAUTHORIZED: 401,
    INVALID_TOKEN: 401,
    TOKEN_EXPIRED: 401,
    MISSING_AUTH_HEADER: 401,
    # 403 Forbidden
    FORBIDDEN: 403,
    INSUFFICIENT_PERMISSIONS: 403,
    ACCESS_DENIED: 403,
    # 404 Not Found
    RESOURCE_NOT_FOUND: 404,
    AGENT_NOT_FOUND: 404,
    DOCUMENT_NOT_FOUND: 404,
    USER_NOT_FOUND: 404,
    CONTENT_SET_NOT_FOUND: 404,
    TEMPLATE_NOT_FOUND: 404,
    # 409 Conflict
    CONFLICT: 409,
    DUPLICATE_RESOURCE: 409,
    STATE_CONFLICT: 409,
    # 422 Unprocessable Entity
    UNPROCESSABLE_ENTITY: 422,
    BUSINESS_RULE_VIOLATION: 422,
    CONTENT_SET_INCOMPLETE: 422,
    FILE_FORMAT_UNSUPPORTED: 422,
    ASSET_TYPE_UNSUPPORTED: 422,
    INVALID_DEPARTMENT: 422,
    # 429 Too Many Requests
    RATE_LIMIT_EXCEEDED: 429,
    QUOTA_EXCEEDED: 429,
    LLM_RATE_LIMIT: 429,
    # 500 Internal Server Error
    INTERNAL_SERVER_ERROR: 500,
    UNEXPECTED_ERROR: 500,
    DATABASE_ERROR: 500,
    CONFIGURATION_ERROR: 500,
    AGENT_PROCESSING_ERROR: 500,
    LLM_ERROR: 502,
    ASSET_GENERATION_FAILED: 500,
    SUMMARIZATION_FAILED: 500,
    CLASSIFICATION_FAILED: 500,
    ANALYSIS_FAILED: 500,
    ORCHESTRATION_FAILED: 500,
    GRAPH_QUERY_FAILED: 500,
    NEO4J_ERROR: 500,
    SUPABASE_ERROR: 500,
    REDIS_ERROR: 500,
    B2_STORAGE_ERROR: 500,
    # 502 Bad Gateway
    BAD_GATEWAY: 502,
    UPSTREAM_ERROR: 502,
    EXTERNAL_API_ERROR: 502,
    ANTHROPIC_API_ERROR: 502,
    LLAMAPARSE_ERROR: 502,
    # 503 Service Unavailable
    SERVICE_UNAVAILABLE: 503,
    MAINTENANCE_MODE: 503,
    AGENT_UNAVAILABLE: 503,
    AGENT_CIRCUIT_OPEN: 503,
    # 504 Gateway Timeout
    GATEWAY_TIMEOUT: 504,
    AGENT_TIMEOUT: 504,
    LLM_TIMEOUT: 504,
    WORKFLOW_TIMEOUT: 504,
}


# Retriable error codes (client can retry these)
RETRIABLE_ERROR_CODES = {
    RATE_LIMIT_EXCEEDED,
    QUOTA_EXCEEDED,
    LLM_RATE_LIMIT,
    SERVICE_UNAVAILABLE,
    AGENT_UNAVAILABLE,
    AGENT_TIMEOUT,
    AGENT_CIRCUIT_OPEN,
    LLM_TIMEOUT,
    GATEWAY_TIMEOUT,
    WORKFLOW_TIMEOUT,
    BAD_GATEWAY,
    UPSTREAM_ERROR,
    EXTERNAL_API_ERROR,
    NEO4J_ERROR,
    REDIS_ERROR,
}


def get_http_status(error_code: str) -> int:
    """Get HTTP status code for an error code."""
    # Check direct mapping first
    if error_code in ERROR_CODE_TO_HTTP_STATUS:
        return ERROR_CODE_TO_HTTP_STATUS[error_code]

    # Handle dynamic *_NOT_FOUND error codes
    if error_code.endswith("_NOT_FOUND"):
        return 404

    # Handle dynamic *_ERROR codes that might be retriable
    if error_code.endswith("_TIMEOUT"):
        return 504

    return 500


def is_retriable(error_code: str) -> bool:
    """Check if an error code represents a retriable error."""
    return error_code in RETRIABLE_ERROR_CODES
